name: My first workflow
on: push 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker HUB
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t fastapi-helloworld:latest .
 
      - name: Test docker
        run: docker build -t fastapi-helloworld:latest .
      
      - name: Launch Docker
        run: docker run -d -p 8000:8000 --name khaled fastapi-helloworld:latest

      - name: Launch Docker
        run: |
          sleep 10
          curl http://localhost:8000/helloworld

      - name: Show container logs (debug)
        run: docker logs khaled

      - name: Show container logs (debug)
        run: docker logs khaled