name: My first workflow
on: push 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
 
      - name: Build Docker image
        run: docker build -t fastapi-helloworld:latest .
 
      - name: Test docker
        run: docker build -t fastapi-helloworld:latest .
      
      - name: Launch Docker
        run: docker run -d -p 8000:8000 fastapi-helloworld:latest
